section:
  boolV: true
  strV: "String2"
  intV: 12
  doubleV: 12.0
  listV:
    - "12"
    - "22"
  section:
    boolV: true
    strV: "String11"
    intV: 11
    doubleV: 11.0
    listV:
      - "12"
      - "22"