main: com.astrainteractive.astratemplate.AstraTemplate
name: AstraTemplate
version: 2.2
author: MakeevRoman
api-version: 1.13
softdepend: []
depend: []
commands:
  atempreload:
  atempgui:
  test:
  atemp:
    usage: |
      /atemp - Перезагружает плагин
