[versions]
# Kotlin
kotlin-version = "1.9.23" # https://github.com/JetBrains/kotlin
kotlin-coroutines = "1.8.1" # https://github.com/Kotlin/kotlinx.coroutines
kotlin-json = "1.6.3" # https://github.com/Kotlin/kotlinx.serialization
kotlin-kaml = "0.59.0" # https://github.com/charleskorn/kaml

# Drivers
driver-jdbc = "3.45.3.0" # https://github.com/xerial/sqlite-jdbc
driver-mysql = "8.0.33" # https://github.com/mysql/mysql-connector-j

# Minecraft
minecraft-version = "1.20.2"
minecraft-velocity = "4.0.0-SNAPSHOT" # https://github.com/PaperMC/Velocity
minecraft-spigot = "1.20.6-R0.1-SNAPSHOT" # https://github.com/PaperMC/Paper
minecraft-papi = "2.11.6" # https://github.com/PlaceholderAPI/PlaceholderAPI
minecraft-protocollib = "5.1.0"
minecraft-wg = "7.0.7"
minecraft-vault = "1.7.1" # https://github.com/MilkBowl/VaultAPI
minecraft-coreprotect = "21.2"
minecraft-astralibs = "3.5.1"
minecraft-bstats = "3.0.2"
minecraft-mockbukkit = "3.86.1"

# Testing
tests-org-testing = "7.10.2"
tests-junit = "4.12"
tests-mockito = "4.0.0"
tests-junit-jupiter-api = "5.10.2"
tests-junit-bom = "5.10.2"

# Fabric
minecraft-fabric-loom = "1.6.11"
minecraft-fabric-kotlin = "1.11.0+"
minecraft-fabric-loader = "0.15.11"
minecraft-fabric-api = "0.99.1+"
minecraft-fabric-yarn = "1.20.2+build.4"

# Shadow
gradle-shadow = "8.1.1"

# BuildConfig
gradle-buildconfig = "5.3.5"

# Exposed
exposed = "0.50.1"

[bundles]
exposed = ["exposed-java-time", "exposed-jdbc", "exposed-dao", "exposed-core"]
minecraft-bukkit = ["minecraft-paper-api", "minecraft-spigot-api", "minecraft-spigot-core", "minecraft-vaultapi", "minecraft-papi"]
testing-kotlin = ["kotlin-coroutines-core", "kotlin-coroutines-coreJvm", "driver-jdbc", "driver-mysql", "kotlin-serialization", "kotlin-serializationJson"]
testing-libs = ["tests-junit-jupiter-api", "tests-org-testing", "tests-junit5", "tests-junit-jupiter"]
kotlin = ["kotlin-coroutines-core", "kotlin-coroutines-coreJvm", "kotlin-serialization", "kotlin-serializationJson", "kotlin-serializationKaml", "kotlin-tooling-core"]

[libraries]

# Kotlin
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-coreJvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlin-coroutines" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin-version" }
kotlin-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-json" }
kotlin-serializationKaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kotlin-kaml" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-version" }
kotlin-tooling-core = { module = "org.jetbrains.kotlin:kotlin-tooling-core", version.ref = "kotlin-version" }

# Shadow
gradle-shadow = { module = "gradle.plugin.com.github.johnrengelman:shadow", version.ref = "gradle-shadow" }

# Drivers
driver-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "driver-jdbc" }
driver-mysql = { module = "mysql:mysql-connector-java", version.ref = "driver-mysql" }

# Testing
tests-junit-bom = { module = "org.junit:junit-bom", version.ref = "tests-junit-bom" }
tests-junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "tests-junit-jupiter-api" }
tests-org-testing = { module = "org.testng:testng", version.ref = "tests-org-testing" }
tests-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
tests-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

# Exposed
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }

# Minecraft
minecraft-paper-api = { module = "io.papermc.paper:paper-api", version.ref = "minecraft-spigot" }
minecraft-spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "minecraft-spigot" }
minecraft-spigot-core = { module = "org.spigotmc:spigot", version.ref = "minecraft-spigot" }
minecraft-velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "minecraft-velocity" }
minecraft-protocollib = { module = "com.comphenix.protocol:ProtocolLib", version.ref = "minecraft-protocollib" }
minecraft-papi = { module = "me.clip:placeholderapi", version.ref = "minecraft-papi" }
minecraft-vaultapi = { module = "com.github.MilkBowl:VaultAPI", version.ref = "minecraft-vault" }
minecraft-bstats = { module = "org.bstats:bstats-bukkit", version.ref = "minecraft-bstats" }
minecraft-mockbukkit = { module = "com.github.MockBukkit:MockBukkit", version.ref = "minecraft-mockbukkit" }

# AstraLibs
minecraft-astralibs-orm = { module = "ru.astrainteractive.astralibs:orm", version.ref = "minecraft-astralibs" }
minecraft-astralibs-core = { module = "ru.astrainteractive.astralibs:core", version.ref = "minecraft-astralibs" }
minecraft-astralibs-menu-bukkit = { module = "ru.astrainteractive.astralibs:menu-bukkit", version.ref = "minecraft-astralibs" }
minecraft-astralibs-core-bukkit = { module = "ru.astrainteractive.astralibs:core-bukkit", version.ref = "minecraft-astralibs" }
minecraft-astralibs-command = { module = "ru.astrainteractive.astralibs:command", version.ref = "minecraft-astralibs" }
minecraft-astralibs-command-bukkit = { module = "ru.astrainteractive.astralibs:command-bukkit", version.ref = "minecraft-astralibs" }

# Fabric
minecraft-fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "minecraft-fabric-kotlin" }
minecraft-fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "minecraft-fabric-loader" }
minecraft-fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "minecraft-fabric-api" }
minecraft-mojang = { module = "com.mojang:minecraft", version.ref = "minecraft-version" }

[plugins]
# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
kotlin-gradle = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-version" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }

# Minecraft
minecraft-fabric-loom = { id = "fabric-loom", version.ref = "minecraft-fabric-loom" }

# Gradle
gradle-shadow = { id = "com.github.johnrengelman.shadow", version.ref = "gradle-shadow" }
gradle-buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "gradle-buildconfig" }